---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:3.23
  amd64: ghcr.io/home-assistant/amd64-base-debian:3.23
args:
  BUILD_DATE: 2025-12-27T00:00:00Z
  BUILD_DESCRIPTION: A Home Assistant Add-On for Maestro UI testing framework
  BUILD_NAME: Maestro Mobile Add-On
  BUILD_REF: main
  BUILD_REPOSITORY: github.com/coder89/hassio-maestro-dev
  BUILD_VERSION: 1.0.0-dev
  DEV_BUILD_DATE: 2025-12-27T00:00:00Z
