build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:latest
  amd64: ghcr.io/home-assistant/amd64-base-debian:latest
  armhf: ghcr.io/home-assistant/armhf-base-debian:latest
  armv7: ghcr.io/home-assistant/armv7-base-debian:latest
  i386: ghcr.io/home-assistant/i386-base-debian:latest
args:
  BUILD_DATE: 2025-12-27T00:00:00Z
  BUILD_DESCRIPTION: A Home Assistant Add-On for Maestro DEV UI testing framework
  BUILD_NAME: Maestro DEV Add-On
  BUILD_REF: main
  BUILD_REPOSITORY: github.com/coder89/hassio-maestro-dev
  BUILD_VERSION: 1.0.0-dev
  DEV_BUILD_DATE: 2025-12-27T00:00:00Z
